#!/usr/bin/env python3
"""Extract quiz answer keys into a server-only module so the Worker can grade
quizzes itself. Answers are NEVER shipped to the browser — grading happens on
the server, so a client cannot forge a score (or, via it, a certificate)."""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "site/assets/data/courses.json"
OUT = ROOT / "functions/api/_quiz-keys.js"


def main():
    data = json.loads(SRC.read_text())
    keys = {}
    for c in data["courses"]:
        if c.get("status") != "published":
            continue
        quiz = c.get("quiz") or []
        if quiz:
            keys[c["id"]] = [int(q["answer"]) for q in quiz]
    body = (
        "// AUTO-GENERATED by scripts/build_quiz_keys.py — do not edit by hand.\n"
        "// Server-only quiz answer keys: { courseId: [correctOptionIndex, ...] }.\n"
        "export const QUIZ_KEYS = " + json.dumps(keys, ensure_ascii=False, separators=(",", ":")) + ";\n"
    )
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(ROOT)} — {len(keys)} courses with quizzes")


if __name__ == "__main__":
    main()
